ARG RUST_VERSION=1.76
FROM rust:${RUST_VERSION}-bullseye

ENV DEBIAN_FRONTEND noninteractive

USER root

# Add rust user
ARG PUID=1000
ENV PUID=${PUID}
ARG PGID=1000
ENV PGID=${PGID}

RUN set -xe; \
  groupadd --gid ${PGID} dev && \
  useradd \
    --uid ${PUID} \
    --gid ${PGID} \
    --no-log-init \
    --create-home \
    dev

# Set timezone
ARG TZ=UTC
ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Install essentials
RUN set -xe; \
  apt-get update -y && \
  apt-get install -y \
    curl \
    git \
    ripgrep \
    zsh && \
  chsh -s $(which zsh) && \
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y -f

# Set system environment variables
ENV LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

# Install Neovim
RUN set -xe; \
  curl -OL https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage && \
  chmod ugo+x nvim.appimage && \
  mv nvim.appimage /usr/local/bin

USER dev

ENV HOME=/home/dev
ENV ZSH_CUSTOM=${HOME}/.oh-my-zsh/custom

WORKDIR ${HOME}

COPY --chown=${PUID}:${PGID} .zshrc ${HOME}

# Setup zsh
RUN set -xe; \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

# Neovim config files
COPY --chown=${PUID}:${PGID} nvim ${HOME}/.config/nvim
COPY --chown=${PUID}:${PGID} starship.toml ${HOME}/.config

# Powerline fonts
RUN mkdir -p \
  ${HOME}/projects \
  ${HOME}/.local/share/fonts \
  ${HOME}/.config/fontconfig/conf.d && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf && \
  mv PowerlineSymbols.otf ${HOME}/.local/share/fonts/ && \
  mv 10-powerline-symbols.conf ${HOME}/.config/fontconfig/conf.d/

# Install rust-analyzer
RUN set -xe; \
  mkdir -p ${HOME}/.local/bin && \
  curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | \
  gunzip -c - > ${HOME}/.local/bin/rust-analyzer && \
  chmod +x ~/.local/bin/rust-analyzer

USER root

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /var/log/lastlog /var/log/faillog

RUN chown -R ${PUID}:${PUID} ${HOME}/.config/nvim ${HOME}/.local

USER dev

WORKDIR ${HOME}/projects
