FROM debian:11-slim

USER root

ARG PUID=1000
ENV PUID=${PUID}
ARG PGID=1000
ENV PGID=${PGID}

# Add dev user
RUN set -xe; \
  groupadd --gid ${PGID} dev && \
  useradd \
    --uid ${PUID} \
    --gid ${PGID} \
    --no-log-init \
    --create-home \
    dev

# Set system environment variables
ENV LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

# Add timezone
ARG TZ=UTC
ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Install essentials
RUN set -xe; \
  apt-get update -y && \
  apt-get install -y \
    build-essential \
    curl \
    git \
    ripgrep \
    unzip \
    zsh && \
  chsh -s $(which zsh) && \
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y -f

# Install Neovim
RUN set -xe; \
  curl -OL https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage && \
  chmod ugo+x nvim.appimage && \
  mv nvim.appimage /usr/local/bin

USER dev

ENV HOME=/home/dev
ENV NVM_DIR=${HOME}/.nvm
ENV ZSH_CUSTOM=${HOME}/.oh-my-zsh/custom

WORKDIR ${HOME}

# Setup zsh
RUN set -xe; \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

COPY --chown=${PUID}:${PGID} .zshrc ${HOME}

# Neovim config files
COPY --chown=${PUID}:${PGID} nvim ${HOME}/.config/nvim
COPY --chown=${PUID}:${PGID} starship.toml ${HOME}/.config

# Install NVM
RUN mkdir -p ${NVM_DIR} && \
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
  . ${NVM_DIR}/nvm.sh

RUN echo '\n\
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" \n\
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \n\
' >> ${HOME}/.zshrc

ARG NODE_VERSION=node
ENV NODE_VERSION=${NODE_VERSION}

RUN set -xe; \
  . ${NVM_DIR}/nvm.sh && \
  nvm install ${NODE_VERSION} && \
  nvm use ${NODE_VERSION} && \
  npm install -g \
    npm@latest \
    typescript \
    typescript-language-server \
    vscode-langservers-extracted

# Powerline fonts
RUN set -xe; \
  mkdir -p \
    ${HOME}/Projects \
    ${HOME}/.local/share/fonts \
    ${HOME}/.config/fontconfig/conf.d && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf && \
  mv PowerlineSymbols.otf ${HOME}/.local/share/fonts/ && \
  mv 10-powerline-symbols.conf ${HOME}/.config/fontconfig/conf.d/

USER root

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /var/log/lastlog /var/log/faillog

USER dev

WORKDIR ${HOME}/Projects
