FROM debian:11-slim

ENV DEBIAN_FRONTEND=noninteractive

USER root
 
# Create non-root user
ARG PUID=1000
ENV PUID=${PUID}
ARG PGID=1000
ENV PGID=${PGID}

# Create user
RUN groupadd --gid ${PGID} dev && \
  useradd \
    --create-home \
    --home /home/dev \
    --shell /bin/bash \
    --uid ${PUID} \
    --gid dev \
    dev

# Set system environment variables
ENV LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

# Set timezone
ARG TZ=UTC
ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Install essentials
RUN set -xe; \
  apt-get update -y && \
  apt-get install -y \
    build-essential \
    curl \
    git \
    ripgrep \
    unzip \
    zsh && \
  chsh -s $(which zsh) && \
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y -f

ARG GO_VERSION=1.23.4
ENV GO_VERSION=${GO_VERSION}

# Install Golang
RUN set -xe; \
  rm -rf /usr/local/go && \
  curl -OL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
  rm go${GO_VERSION}.linux-amd64.tar.gz

# Install Neovim
RUN set -xe; \
  curl -OL https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage && \
  chmod ugo+x nvim.appimage && \
  mv nvim.appimage /usr/local/bin

USER dev

ENV HOME=/home/dev
ENV ZSH_CUSTOM=${HOME}/.oh-my-zsh/custom

WORKDIR ${HOME}

RUN set -xe; \
  /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest && \
  /usr/local/go/bin/go install golang.org/x/tools/gopls@latest && \
  /usr/local/go/bin/go install golang.org/x/tools/cmd/goimports@latest

# Setup zsh
RUN set -xe; \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

COPY --chown=${PUID}:${PGID} .zshrc ${HOME}

# Powerline fonts
RUN set -xe; \
  mkdir -p \
    ${HOME}/Projects \
    ${HOME}/.local/share/fonts \
    ${HOME}/.config/fontconfig/conf.d && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf && \
  curl -O https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf && \
  mv PowerlineSymbols.otf ${HOME}/.local/share/fonts/ && \
  mv 10-powerline-symbols.conf ${HOME}/.config/fontconfig/conf.d/

# Neovim config files
COPY --chown=${PUID}:${PGID} nvim ${HOME}/.config/nvim
COPY --chown=${PUID}:${PGID} starship.toml ${HOME}/.config

USER root

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /var/log/lastlog /var/log/faillog

RUN chown -R ${PUID}:${PUID} ${HOME}/.config/nvim ${HOME}/.local

USER dev

WORKDIR ${HOME}/Projects
